name: "Release"
on:
  # push to master trigger creating release version
  push:
    branches:
      - master
jobs:
  job1:
    name: Releases
      - name: Push to Releases
            uses: ncipollo/release-action@v1
            with:
              artifacts: "build/app/outputs/flutter-apk/app-release.apk"
              tag: v1.0.${{ github.run_number }}
              token: ${{ secrets.TOKEN }}